### ISSUE TITLE
conv-paint "train on full project"

### ISSUE THREAD

**Issue by StojiljkovicVetAna** [guiwitz/napari-morphodynamics#10]
Currently the plugin is designed to analyze and visualize one cell at a time. Therefore, the option "train model on full project" in the conv-paint method is irrelevant and should be hidden together with the tab "Files" and the "use project" checkbox option.

**Comment by guiwitz** [comment]
This is fixed in dc947d7f5c69eb364d3ae1e31cdf43faa3c0c2cb
