### ISSUE TITLE
No module named 'matplotlib.backends.backend_qtagg

### ISSUE THREAD

**Issue by fabricesenger** [guiwitz/napari-morphodynamics#13]
Hello Guillaume !
While working with convpaint I wanted to give morphodynamics a try. I installed it via napari and when i start th plugin i get this error :

RuntimeError: Failed to import command at 'napari_morphodynamics.napari_gui:MorphoWidget': No module named 'matplotlib.backends.backend_qtagg'

Thank you for your support,

Fabrice.

**Comment by guiwitz** [comment]
Hi Fabrice,
This is strange as the Qt backend should be available from napari. Do you use conda for installation? If yes can you run ```conda list``` in the environment you used and paste the output here?

**Comment by fabricesenger** [comment]
Here we go : 

# packages in environment at C:\Users\fabrice_senger\miniconda3\envs\napari-env: 
# 
# Name Version Build Channel 
aicsimageio 4.9.4 pypi_0 pypi 
aiofiles 22.1.0 pypi_0 pypi 
aiosqlite 0.18.0 pypi_0 pypi 
alabaster 0.7.13 pypi_0 pypi 
anyio 3.6.2 pypi_0 pypi 
apoc 0.12.0 pypi_0 pypi 
app-model 0.1.2 pypi_0 pypi 
appdirs 1.4.4 pypi_0 pypi 
argon2-cffi 21.3.0 pypi_0 pypi 
argon2-cffi-bindings 21.2.0 pypi_0 pypi 
arrow 1.2.3 pypi_0 pypi 
asciitree 0.3.3 pypi_0 pypi 
asttokens 2.2.1 pypi_0 pypi 
attrs 22.2.0 pypi_0 pypi 
autopep8 2.0.2 pypi_0 pypi 
babel 2.12.1 pypi_0 pypi 
backcall 0.2.0 pypi_0 pypi 
beautifulsoup4 4.11.2 pypi_0 pypi 
bleach 6.0.0 pypi_0 pypi 
bokeh 2.4.3 pypi_0 pypi 
btrack 0.6.4 pypi_0 pypi 
build 0.10.0 pypi_0 pypi 
bzip2 1.0.8 h8ffe710_4 conda-forge 
ca-certificates 2023.01.10 haa95532_0 anaconda 
cachey 0.2.1 pypi_0 pypi 
cellpose 2.2 pypi_0 pypi 
cellpose-napari 0.1.5 pypi_0 pypi 
cellpose-omni 0.9.1 pypi_0 pypi 
certifi 2022.12.7 pypi_0 pypi 
cffi 1.15.1 pypi_0 pypi 
charset-normalizer 3.1.0 pypi_0 pypi 
classifier 2.0 pypi_0 pypi 
click 8.1.3 pypi_0 pypi 
cloudpickle 2.2.1 pypi_0 pypi 
cmap 0.1.3 pypi_0 pypi 
collections-undo 0.0.7 pypi_0 pypi 
colorama 0.4.6 pypi_0 pypi 
comm 0.1.2 pypi_0 pypi 
confuse 2.0.1 pypi_0 pypi 
cvxopt 1.3.2 pypi_0 pypi 
cython 0.29.33 pypi_0 pypi 
czifile 2019.7.2 pypi_0 pypi 
dask 2023.3.1 pypi_0 pypi 
dask-jobqueue 0.8.2 pypi_0 pypi 
debugpy 1.6.6 pypi_0 pypi 
decorator 5.1.1 pypi_0 pypi 
defusedxml 0.7.1 pypi_0 pypi 
deprecated 1.2.13 pypi_0 pypi 
devbio-napari 0.10.1 pypi_0 pypi 
dill 0.3.7 pypi_0 pypi 
distributed 2023.3.1 pypi_0 pypi 
dnspython 2.3.0 pypi_0 pypi 
docstring-parser 0.15 pypi_0 pypi 
docutils 0.17.1 pypi_0 pypi 
edt 2.3.1 pypi_0 pypi 
einops 0.7.0 pypi_0 pypi 
elementpath 4.0.1 pypi_0 pypi 
email-validator 1.3.1 pypi_0 pypi 
entrypoints 0.4 pypi_0 pypi 
et-xmlfile 1.1.0 pypi_0 pypi 
exceptiongroup 1.1.1 pypi_0 pypi 
executing 1.2.0 pypi_0 pypi 
fasteners 0.18 pypi_0 pypi 
fastjsonschema 2.16.3 pypi_0 pypi 
fastremap 1.13.4 pypi_0 pypi 
filelock 3.13.1 pypi_0 pypi 
fonticon-fontawesome6 6.4.0 pypi_0 pypi 
fqdn 1.5.1 pypi_0 pypi 
freetype-py 2.3.0 pypi_0 pypi 
fsspec 2023.3.0 pypi_0 pypi 
funcsigs 1.0.2 pypi_0 pypi 
griottes 0.1.0 pypi_0 pypi 
h5py 3.8.0 pypi_0 pypi 
hdbscan 0.8.29 pypi_0 pypi 
heapdict 1.0.1 pypi_0 pypi 
hsluv 5.0.3 pypi_0 pypi 
idna 3.4 pypi_0 pypi 
igraph 0.11.3 pypi_0 pypi 
imagecodecs 2023.1.23 pypi_0 pypi 
imageio 2.31.1 pypi_0 pypi 
imageio-ffmpeg 0.4.8 pypi_0 pypi 
imagesize 1.4.1 pypi_0 pypi 
imglyb 2.1.0 pypi_0 pypi 
importlib-metadata 6.0.0 pypi_0 pypi 
in-n-out 0.1.7 pypi_0 pypi 
iniconfig 2.0.0 pypi_0 pypi 
ipycanvas 0.13.1 pypi_0 pypi 
ipyevents 2.0.1 pypi_0 pypi 
ipykernel 6.21.3 pypi_0 pypi 
ipython 8.11.0 pypi_0 pypi 
ipython-genutils 0.2.0 pypi_0 pypi 
ipywidgets 8.0.4 pypi_0 pypi 
isoduration 20.11.0 pypi_0 pypi 
jedi 0.18.2 pypi_0 pypi 
jgo 1.0.5 pypi_0 pypi 
jinja2 3.1.2 pypi_0 pypi 
joblib 1.2.0 pypi_0 pypi 
jpype1 1.4.1 pypi_0 pypi 
json5 0.9.11 pypi_0 pypi 
jsonpointer 2.3 pypi_0 pypi 
jsonschema 4.17.3 pypi_0 pypi 
jupyter 1.0.0 pypi_0 pypi 
jupyter-client 8.0.3 pypi_0 pypi 
jupyter-console 6.6.3 pypi_0 pypi 
jupyter-core 5.2.0 pypi_0 pypi 
jupyter-events 0.6.3 pypi_0 pypi 
jupyter-server 1.23.6 pypi_0 pypi 
jupyter-server-fileid 0.8.0 pypi_0 pypi 
jupyter-server-ydoc 0.6.1 pypi_0 pypi 
jupyter-ydoc 0.2.3 pypi_0 pypi 
jupyterlab 3.6.1 pypi_0 pypi 
jupyterlab-pygments 0.2.2 pypi_0 pypi 
jupyterlab-server 2.20.0 pypi_0 pypi 
jupyterlab-widgets 3.0.5 pypi_0 pypi 
jupytext 1.14.5 pypi_0 pypi 
labeling 0.1.13 pypi_0 pypi 
lazy-loader 0.3 pypi_0 pypi 
libffi 3.4.2 h8ffe710_5 conda-forge 
libsqlite 3.40.0 hcfcfb64_0 conda-forge 
libzlib 1.2.13 hcfcfb64_4 conda-forge 
light-the-torch 0.7.5 pypi_0 pypi 
llvmlite 0.39.1 pypi_0 pypi 
local-migrator 0.1.9 pypi_0 pypi 
locket 1.0.0 pypi_0 pypi 
loguru 0.6.0 pypi_0 pypi 
lxml 4.9.2 pypi_0 pypi 
lz4 4.3.2 pypi_0 pypi 
magicgui 0.7.2 pypi_0 pypi 
mahotas 1.4.13 pypi_0 pypi 
mako 1.2.4 pypi_0 pypi 
markdown-it-py 2.2.0 pypi_0 pypi 
markupsafe 2.1.2 pypi_0 pypi 
matplotlib-inline 0.1.6 pypi_0 pypi 
matplotlib-scalebar 0.8.1 pypi_0 pypi 
mdit-py-plugins 0.3.5 pypi_0 pypi 
mdurl 0.1.2 pypi_0 pypi 
mgen 1.2.1 pypi_0 pypi 
microfilm 0.2.1 pypi_0 pypi 
mistune 2.0.5 pypi_0 pypi 
morphodynamics 0.4.1 pypi_0 pypi 
mpmath 1.3.0 pypi_0 pypi 
msgpack 1.0.7 pypi_0 pypi 
mypy-extensions 1.0.0 pypi_0 pypi 
napari 0.4.18 pypi_0 pypi 
napari-accelerated-pixel-and-object-classification 0.14.1 pypi_0 pypi 
napari-animation 0.0.5 pypi_0 pypi 
napari-annotation-project 0.1.1 pypi_0 pypi 
napari-assistant 0.4.7 pypi_0 pypi 
napari-bioformats 0.2.1 pypi_0 pypi 
napari-brightness-contrast 0.1.8 pypi_0 pypi 
napari-clusters-plotter 0.7.3 pypi_0 pypi 
napari-console 0.0.9 pypi_0 pypi 
napari-convpaint 0.2.1 pypi_0 pypi 
napari-crop 0.1.7 pypi_0 pypi 
napari-curtain 0.1.1 pypi_0 pypi 
napari-czifile2 0.2.7 pypi_0 pypi 
napari-folder-browser 0.1.3 pypi_0 pypi 
napari-guitils 0.1.0 pypi_0 pypi 
napari-imagej 0.1.0 pypi_0 pypi 
napari-layer-details-display 0.1.5 pypi_0 pypi 
napari-matplotlib 1.2.0 pypi_0 pypi 
napari-morphodynamics 0.1.1 pypi_0 pypi 
napari-plot-profile 0.2.2 pypi_0 pypi 
napari-plugin-engine 0.2.0 pypi_0 pypi 
napari-plugin-manager 0.1.0a2 pypi_0 pypi 
napari-pyclesperanto-assistant 0.22.1 pypi_0 pypi 
napari-pystackreg 0.1.4 pypi_0 pypi 
napari-roi 0.1.8 pypi_0 pypi 
napari-segment-blobs-and-things-with-membranes 0.3.7 pypi_0 pypi 
napari-simpleitk-image-processing 0.4.5 pypi_0 pypi 
napari-skimage-regionprops 0.10.1 pypi_0 pypi 
napari-svg 0.1.10 pypi_0 pypi 
napari-tabu 0.1.5 pypi_0 pypi 
napari-time-slicer 0.4.9 pypi_0 pypi 
napari-tools-menu 0.1.19 pypi_0 pypi 
napari-workflow-inspector 0.2.2 pypi_0 pypi 
napari-workflow-optimizer 0.1.4 pypi_0 pypi 
napari-workflows 0.2.10 pypi_0 pypi 
natsort 8.3.1 pypi_0 pypi 
nbclassic 0.5.3 pypi_0 pypi 
nbclient 0.7.2 pypi_0 pypi 
nbconvert 7.2.10 pypi_0 pypi 
nbformat 5.7.3 pypi_0 pypi 
ncolor 1.2.1 pypi_0 pypi 
nest-asyncio 1.5.6 pypi_0 pypi 
networkx 3.0 pypi_0 pypi 
nme 0.1.8 pypi_0 pypi 
notebook 6.5.3 pypi_0 pypi 
notebook-shim 0.2.2 pypi_0 pypi 
npe2 0.6.2 pypi_0 pypi 
numba 0.56.4 pypi_0 pypi 
numcodecs 0.11.0 pypi_0 pypi 
numpy 1.23.5 pypi_0 pypi 
numpydoc 1.5.0 pypi_0 pypi 
oiffile 2022.9.29 pypi_0 pypi 
ome-types 0.3.3 pypi_0 pypi 
omnipose 0.4.4 pypi_0 pypi 
opencv-python-headless 4.7.0.72 pypi_0 pypi 
openpyxl 3.1.2 pypi_0 pypi 
openssl 3.1.0 hcfcfb64_0 conda-forge 
packaging 23.0 pypi_0 pypi 
pandas 2.0.3 pypi_0 pypi 
pandocfilters 1.5.0 pypi_0 pypi 
parso 0.8.3 pypi_0 pypi 
partd 1.3.0 pypi_0 pypi 
partseg 0.15.2 pypi_0 pypi 
partsegcore-compiled-backend 0.15.1 pypi_0 pypi 
partsegdata 0.10.0 pypi_0 pypi 
pbr 6.0.0 pypi_0 pypi 
peakdetect 1.2 pypi_0 pypi 
pickleshare 0.7.5 pypi_0 pypi 
pillow 9.4.0 pypi_0 pypi 
pims 0.6.1 pypi_0 pypi 
pint 0.20.1 pypi_0 pypi 
pip 23.2.1 pypi_0 pypi 
pixel 0.4.1 pypi_0 pypi 
platformdirs 3.1.1 pypi_0 pypi 
pluggy 1.0.0 pypi_0 pypi 
pooch 1.7.0 pypi_0 pypi 
prometheus-client 0.16.0 pypi_0 pypi 
prompt-toolkit 3.0.38 pypi_0 pypi 
psutil 5.9.4 pypi_0 pypi 
psygnal 0.8.1 pypi_0 pypi 
pure-eval 0.2.2 pypi_0 pypi 
pyarrow 14.0.1 pypi_0 pypi 
pyclesperanto-prototype 0.23.3 pypi_0 pypi 
pycodestyle 2.10.0 pypi_0 pypi 
pycparser 2.21 pypi_0 pypi 
pydantic 1.10.6 pypi_0 pypi 
pygments 2.14.0 pypi_0 pypi 
pyimagej 1.4.1 pypi_0 pypi 
pynndescent 0.5.8 pypi_0 pypi 
pyopencl 2022.3.1 pypi_0 pypi 
pyopengl 3.1.6 pypi_0 pypi 
pyperclip 1.8.2 pypi_0 pypi 
pyproject-hooks 1.0.0 pypi_0 pypi 
pyqt5 5.15.9 pypi_0 pypi 
pyqt5-qt5 5.15.2 pypi_0 pypi 
pyqt5-sip 12.11.1 pypi_0 pypi 
pyqtgraph 0.13.3 pypi_0 pypi 
pyrsistent 0.19.3 pypi_0 pypi 
pystackreg 0.2.7 pypi_0 pypi 
pytest 7.2.2 pypi_0 pypi 
python 3.9.16 h4de0772_0_cpython conda-forge 
python-json-logger 2.0.7 pypi_0 pypi 
pytomlpp 1.0.11 pypi_0 pypi 
pytools 2022.1.14 pypi_0 pypi 
pytorch-ranger 0.1.1 pypi_0 pypi 
pywin32 305 pypi_0 pypi 
pywinpty 2.0.10 pypi_0 pypi 
pyzmq 25.0.1 pypi_0 pypi 
qt-command-palette 0.0.6 pypi_0 pypi 
qtawesome 1.2.3 pypi_0 pypi 
qtconsole 5.4.1 pypi_0 pypi 
qtpy 2.3.0 pypi_0 pypi 
redlionfish 0.9 pypi_0 pypi 
reikna 0.8.0 pypi_0 pypi 
requests 2.28.2 pypi_0 pypi 
resource-backed-dask-array 0.1.0 pypi_0 pypi 
rfc3339-validator 0.1.4 pypi_0 pypi 
rfc3986-validator 0.1.1 pypi_0 pypi 
rich 13.3.2 pypi_0 pypi 
scikit-image 0.21.0 pypi_0 pypi 
scikit-learn 1.2.2 pypi_0 pypi 
scipy 1.9.1 pypi_0 pypi 
scyjava 1.9.1 pypi_0 pypi 
seaborn 0.12.2 pypi_0 pypi 
segment-anything 1.0 pypi_0 pypi 
send2trash 1.8.0 pypi_0 pypi 
sentry-sdk 1.29.2 pypi_0 pypi 
setuptools 67.6.0 pyhd8ed1ab_0 conda-forge 
simpleitk 2.2.1 pypi_0 pypi 
six 1.16.0 pypi_0 pypi 
skan 0.11.1 pypi_0 pypi 
slicerator 1.1.0 pypi_0 pypi 
sniffio 1.3.0 pypi_0 pypi 
snowballstemmer 2.2.0 pypi_0 pypi 
sortedcontainers 2.4.0 pypi_0 pypi 
soupsieve 2.4 pypi_0 pypi 
sphinx 4.5.0 pypi_0 pypi 
sphinxcontrib-applehelp 1.0.4 pypi_0 pypi 
sphinxcontrib-devhelp 1.0.2 pypi_0 pypi 
sphinxcontrib-htmlhelp 2.0.1 pypi_0 pypi 
sphinxcontrib-jsmath 1.0.1 pypi_0 pypi 
sphinxcontrib-qthelp 1.0.3 pypi_0 pypi 
sphinxcontrib-serializinghtml 1.1.5 pypi_0 pypi 
stack-data 0.6.2 pypi_0 pypi 
stackview 0.5.2 pypi_0 pypi 
superqt 0.4.1 pypi_0 pypi 
sympy 1.12 pypi_0 pypi 
tabulate 0.9.0 pypi_0 pypi 
tblib 3.0.0 pypi_0 pypi 
terminado 0.17.1 pypi_0 pypi 
texttable 1.7.0 pypi_0 pypi 
the-segmentation-game 0.2.0 pypi_0 pypi 
threadpoolctl 3.1.0 pypi_0 pypi 
tifffile 2023.2.28 pypi_0 pypi 
tinycss2 1.2.1 pypi_0 pypi 
tk 8.6.12 h8ffe710_0 conda-forge 
toml 0.10.2 pypi_0 pypi 
tomli 2.0.1 pypi_0 pypi 
toolz 0.12.0 pypi_0 pypi 
torch 2.0.1 pypi_0 pypi 
torch-optimizer 0.3.0 pypi_0 pypi 
torchaudio 0.10.1+cu113 pypi_0 pypi 
torchvf 0.1.3 pypi_0 pypi 
torchvision 0.15.2 pypi_0 pypi 
tornado 6.2 pypi_0 pypi 
tqdm 4.66.1 pypi_0 pypi 
traceback-with-variables 2.0.4 pypi_0 pypi 
traitlets 5.9.0 pypi_0 pypi 
transforms3d 0.4.1 pypi_0 pypi 
typer 0.7.0 pypi_0 pypi 
typing-extensions 4.5.0 pypi_0 pypi 
tzdata 2023.3 pypi_0 pypi 
ucrt 10.0.22621.0 h57928b3_0 conda-forge 
umap-learn 0.5.3 pypi_0 pypi 
uri-template 1.2.0 pypi_0 pypi 
urllib3 1.26.15 pypi_0 pypi 
vc 14.3 hb6edc58_10 conda-forge 
vispy 0.12.2 pypi_0 pypi 
vs2015_runtime 14.34.31931 h4c5c07a_10 conda-forge 
wcwidth 0.2.6 pypi_0 pypi 
webcolors 1.12 pypi_0 pypi 
webencodings 0.5.1 pypi_0 pypi 
websocket-client 1.5.1 pypi_0 pypi 
wheel 0.40.0 pyhd8ed1ab_0 conda-forge 
widgetsnbextension 4.0.5 pypi_0 pypi 
win32-setctime 1.1.0 pypi_0 pypi 
wrapt 1.15.0 pypi_0 pypi 
xarray 2023.2.0 pypi_0 pypi 
xlrd 2.0.1 pypi_0 pypi 
xlsxwriter 3.1.2 pypi_0 pypi 
xmlschema 2.2.2 pypi_0 pypi 
xz 5.2.6 h8d14728_0 conda-forge 
y-py 0.5.9 pypi_0 pypi 
ypy-websocket 0.8.2 pypi_0 pypi 
zarr 2.14.2 pypi_0 pypi 
zict 3.0.0 pypi_0 pypi 
zipp 3.15.0 pypi_0 pypi 



De: "Guillaume Witz" ***@***.***> 
À: "guiwitz/napari-morphodynamics" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 15 Décembre 2023 16:45:38 
Objet: Re: [guiwitz/napari-morphodynamics] No module named 'matplotlib.backends.backend_qtagg (Issue #13) 





Hi Fabrice, 
This is strange as the Qt backend should be available from napari. Do you use conda for installation? If yes can you run conda list in the environment you used and paste the output here?

**Comment by guiwitz** [comment]
It looks like matplotlib is not available as a package?  It's really odd given the number of packages depending on matplotlib that you have in your environment. Did you uninstall it? In any case can you try to pip or conda install matplotlib and see if that solves your problem? In general your environment is quite large, so I wouldn't be surprised if at some point it becomes unstable. Maybe you can try to install just this plugin in a fresh environment.

**Comment by fabricesenger** [comment]
Hello,  
Indeed, I have a lot of stuff installed. I'll try your suggestion on Monday. I left my computer for the WE. Thank you and good WE.  
     

-----Message original-----

De: Guillaume ***@***.***>
à: guiwitz ***@***.***>
Cc: fabricesenger ***@***.***>; Author ***@***.***>
Envoyé: vendredi 15 décembre 2023 18:10 CET
Sujet : Re: [guiwitz/napari-morphodynamics] No module named 'matplotlib.backends.backend_qtagg (Issue #13)

 

  It looks like matplotlib is not available as a package? It's really odd given the number of packages depending on matplotlib that you have in your environment. Did you uninstall it? In any case can you try to pip or conda install matplotlib and see if that solves your problem? In general your environment is quite large, so I wouldn't be surprised if at some point it becomes unstable. Maybe you can try to install just this plugin in a fresh environment. —

**Comment by fabricesenger** [comment]
Hello, 

so I installed matplotlib and crashed my install. 
Will start with a fresh one and let you know. 

Fabrice. 


De: "Guillaume Witz" ***@***.***> 
À: "guiwitz/napari-morphodynamics" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 15 Décembre 2023 18:10:35 
Objet: Re: [guiwitz/napari-morphodynamics] No module named 'matplotlib.backends.backend_qtagg (Issue #13) 





It looks like matplotlib is not available as a package? It's really odd given the number of packages depending on matplotlib that you have in your environment. Did you uninstall it? In any case can you try to pip or conda install matplotlib and see if that solves your problem? In general your environment is quite large, so I wouldn't be surprised if at some point it becomes unstable. Maybe you can try to install just this plugin in a fresh environment.

**Comment by fabricesenger** [comment]
Bonjour,

now i have a new env with cellpose convpaint and morphodynamics, had to open a new trhread tough.

Fabrice.

**Comment by guiwitz** [comment]
Ok. I close this one for the moment and we can keep discussing in the other.
