### ISSUE TITLE
key combination A already used!

### ISSUE THREAD

**Issue by fabricesenger** [guiwitz/napari-morphodynamics#14]
Hello,

sorry for alll the issues i raise, here the code 

File ~\miniconda3\envs\napari-env\lib\site-packages\napari\utils\key_bindings.py:286, in bind_key(keymap={'A': <bound method ConvPaintWidget.hide_annotation of...ari_convpaint.conv_paint.ConvPaintWidget object>>, 'R': <bound method ConvPaintWidget.hide_prediction of...ari_convpaint.conv_paint.ConvPaintWidget object>>}, key='A', func=<bound method ConvPaintWidget.hide_annotation of...ari_convpaint.conv_paint.ConvPaintWidget object>>, overwrite=False)
    283     key = normalize_key_combo(key)
    285 if func is not None and key in keymap and not overwrite:
--> 286     raise ValueError(
        trans = <napari.utils.translations.TranslationBundle object at 0x000002A5406F3910>
        key = 'A'
    287         trans._(
    288             'key combination {key} already used! specify \'overwrite=True\' to bypass this check',
    289             deferred=True,
    290             key=key,
    291         )
    292     )
    294 unbound = keymap.pop(key, None)
    296 if func is not None:

ValueError: key combination A already used! specify 'overwrite=True' to bypass this check

**Comment by guiwitz** [comment]
Hi,
no worries, I'm grateful that people test the software in its very alpha stage!
When exactly does this error appear and is this the full error? Can you list again the installed packages with conda list? I don't think this is caused by this plugin as it doesn't have any key bindings. Probably another installed in the same environment.

**Comment by fabricesenger** [comment]
Here we go : 

# packages in environment at C:\Users\fabrice_senger\miniconda3\envs\napari-env: 
# 
# Name Version Build Channel 
aicsimageio 4.14.0 pypi_0 pypi 
aiobotocore 2.5.4 pypi_0 pypi 
aiohttp 3.9.1 pypi_0 pypi 
aioitertools 0.11.0 pypi_0 pypi 
aiosignal 1.3.1 pypi_0 pypi 
alabaster 0.7.13 pypi_0 pypi 
app-model 0.2.3 pypi_0 pypi 
appdirs 1.4.4 pypi_0 pypi 
asciitree 0.3.3 pypi_0 pypi 
asttokens 2.4.1 pypi_0 pypi 
async-timeout 4.0.3 pypi_0 pypi 
attrs 23.1.0 pypi_0 pypi 
babel 2.14.0 pypi_0 pypi 
bokeh 3.3.2 pypi_0 pypi 
botocore 1.31.17 pypi_0 pypi 
build 1.0.3 pypi_0 pypi 
bzip2 1.0.8 hcfcfb64_5 conda-forge 
ca-certificates 2023.11.17 h56e8100_0 conda-forge 
cachey 0.2.1 pypi_0 pypi 
cellpose 2.2.3 pypi_0 pypi 
cellpose-napari 0.1.5 pypi_0 pypi 
certifi 2023.11.17 pypi_0 pypi 
charset-normalizer 3.3.2 pypi_0 pypi 
click 8.1.7 pypi_0 pypi 
cloudpickle 3.0.0 pypi_0 pypi 
cmap 0.1.3 pypi_0 pypi 
colorama 0.4.6 pypi_0 pypi 
comm 0.2.0 pypi_0 pypi 
contourpy 1.2.0 pypi_0 pypi 
dask 2023.12.1 pypi_0 pypi 
dask-jobqueue 0.8.2 pypi_0 pypi 
debugpy 1.8.0 pypi_0 pypi 
decorator 5.1.1 pypi_0 pypi 
dill 0.3.7 pypi_0 pypi 
distributed 2023.12.1 pypi_0 pypi 
docstring-parser 0.15 pypi_0 pypi 
docutils 0.17.1 pypi_0 pypi 
einops 0.7.0 pypi_0 pypi 
elementpath 4.1.5 pypi_0 pypi 
exceptiongroup 1.2.0 pypi_0 pypi 
executing 2.0.1 pypi_0 pypi 
fasteners 0.19 pypi_0 pypi 
fastremap 1.14.0 pypi_0 pypi 
filelock 3.13.1 pypi_0 pypi 
fonttools 4.46.0 pypi_0 pypi 
freetype-py 2.4.0 pypi_0 pypi 
frozenlist 1.4.1 pypi_0 pypi 
fsspec 2023.6.0 pypi_0 pypi 
h5py 3.10.0 pypi_0 pypi 
heapdict 1.0.1 pypi_0 pypi 
hsluv 5.0.4 pypi_0 pypi 
idna 3.6 pypi_0 pypi 
imagecodecs 2023.9.18 pypi_0 pypi 
imageio 2.33.1 pypi_0 pypi 
imagesize 1.4.1 pypi_0 pypi 
importlib-metadata 7.0.0 pypi_0 pypi 
importlib-resources 6.1.1 pypi_0 pypi 
in-n-out 0.1.9 pypi_0 pypi 
ipykernel 6.27.1 pypi_0 pypi 
ipython 8.18.1 pypi_0 pypi 
ipywidgets 8.1.1 pypi_0 pypi 
jedi 0.19.1 pypi_0 pypi 
jinja2 3.1.2 pypi_0 pypi 
jmespath 1.0.1 pypi_0 pypi 
joblib 1.3.2 pypi_0 pypi 
jsonschema 4.20.0 pypi_0 pypi 
jsonschema-specifications 2023.11.2 pypi_0 pypi 
jupyter-client 8.6.0 pypi_0 pypi 
jupyter-core 5.5.1 pypi_0 pypi 
jupyterlab-widgets 3.0.9 pypi_0 pypi 
lazy-loader 0.3 pypi_0 pypi 
libffi 3.4.2 h8ffe710_5 conda-forge 
libsqlite 3.44.2 hcfcfb64_0 conda-forge 
libzlib 1.2.13 hcfcfb64_5 conda-forge 
llvmlite 0.41.1 pypi_0 pypi 
locket 1.0.0 pypi_0 pypi 
lxml 4.9.3 pypi_0 pypi 
lz4 4.3.2 pypi_0 pypi 
magicgui 0.8.1 pypi_0 pypi 
markdown-it-py 3.0.0 pypi_0 pypi 
markupsafe 2.1.3 pypi_0 pypi 
matplotlib 3.8.2 pypi_0 pypi 
matplotlib-inline 0.1.6 pypi_0 pypi 
matplotlib-scalebar 0.8.1 pypi_0 pypi 
mdurl 0.1.2 pypi_0 pypi 
microfilm 0.2.1 pypi_0 pypi 
morphodynamics 0.4.1 pypi_0 pypi 
mpmath 1.3.0 pypi_0 pypi 
msgpack 1.0.7 pypi_0 pypi 
multidict 6.0.4 pypi_0 pypi 
mypy-extensions 1.0.0 pypi_0 pypi 
napari 0.4.18 pypi_0 pypi 
napari-annotation-project 0.1.1 pypi_0 pypi 
napari-console 0.0.9 pypi_0 pypi 
napari-convpaint 0.2.1 pypi_0 pypi 
napari-guitils 0.1.0 pypi_0 pypi 
napari-matplotlib 1.2.0 pypi_0 pypi 
napari-morphodynamics 0.1.1 pypi_0 pypi 
napari-plugin-engine 0.2.0 pypi_0 pypi 
napari-plugin-manager 0.1.0a2 pypi_0 pypi 
napari-svg 0.1.10 pypi_0 pypi 
natsort 8.4.0 pypi_0 pypi 
nest-asyncio 1.5.8 pypi_0 pypi 
networkx 3.2.1 pypi_0 pypi 
npe2 0.7.3 pypi_0 pypi 
numba 0.58.1 pypi_0 pypi 
numcodecs 0.12.1 pypi_0 pypi 
numpy 1.26.2 pypi_0 pypi 
numpydoc 1.5.0 pypi_0 pypi 
ome-types 0.4.5 pypi_0 pypi 
ome-zarr 0.8.3 pypi_0 pypi 
opencv-python-headless 4.8.1.78 pypi_0 pypi 
openssl 3.2.0 hcfcfb64_1 conda-forge 
packaging 23.2 pypi_0 pypi 
pandas 2.1.4 pypi_0 pypi 
parso 0.8.3 pypi_0 pypi 
partd 1.4.1 pypi_0 pypi 
pillow 10.1.0 pypi_0 pypi 
pint 0.23 pypi_0 pypi 
pip 23.3.2 pypi_0 pypi 
platformdirs 4.1.0 pypi_0 pypi 
pooch 1.8.0 pypi_0 pypi 
prompt-toolkit 3.0.43 pypi_0 pypi 
psutil 5.9.7 pypi_0 pypi 
psygnal 0.9.5 pypi_0 pypi 
pure-eval 0.2.2 pypi_0 pypi 
pyarrow 14.0.2 pypi_0 pypi 
pyarrow-hotfix 0.6 pypi_0 pypi 
pyconify 0.1.6 pypi_0 pypi 
pydantic 1.10.13 pypi_0 pypi 
pydantic-compat 0.1.2 pypi_0 pypi 
pygments 2.17.2 pypi_0 pypi 
pyopengl 3.1.7 pypi_0 pypi 
pyproject-hooks 1.0.0 pypi_0 pypi 
pyqt5 5.15.10 pypi_0 pypi 
pyqt5-qt5 5.15.2 pypi_0 pypi 
pyqt5-sip 12.13.0 pypi_0 pypi 
python 3.9.18 h4de0772_0_cpython conda-forge 
pywin32 306 pypi_0 pypi 
pyyaml 6.0.1 pypi_0 pypi 
pyzmq 25.1.2 pypi_0 pypi 
qtconsole 5.5.1 pypi_0 pypi 
qtpy 2.4.1 pypi_0 pypi 
referencing 0.32.0 pypi_0 pypi 
requests 2.31.0 pypi_0 pypi 
resource-backed-dask-array 0.1.0 pypi_0 pypi 
rich 13.7.0 pypi_0 pypi 
roifile 2023.8.30 pypi_0 pypi 
rpds-py 0.15.2 pypi_0 pypi 
s3fs 2023.6.0 pypi_0 pypi 
scikit-image 0.22.0 pypi_0 pypi 
scikit-learn 1.3.2 pypi_0 pypi 
scipy 1.11.4 pypi_0 pypi 
setuptools 68.2.2 pyhd8ed1ab_0 conda-forge 
six 1.16.0 pypi_0 pypi 
snowballstemmer 2.2.0 pypi_0 pypi 
sortedcontainers 2.4.0 pypi_0 pypi 
sphinx 4.5.0 pypi_0 pypi 
sphinxcontrib-applehelp 1.0.4 pypi_0 pypi 
sphinxcontrib-devhelp 1.0.2 pypi_0 pypi 
sphinxcontrib-htmlhelp 2.0.1 pypi_0 pypi 
sphinxcontrib-jsmath 1.0.1 pypi_0 pypi 
sphinxcontrib-qthelp 1.0.3 pypi_0 pypi 
sphinxcontrib-serializinghtml 1.1.5 pypi_0 pypi 
stack-data 0.6.3 pypi_0 pypi 
superqt 0.6.1 pypi_0 pypi 
sympy 1.12 pypi_0 pypi 
tblib 3.0.0 pypi_0 pypi 
threadpoolctl 3.2.0 pypi_0 pypi 
tifffile 2023.2.28 pypi_0 pypi 
tinycss2 1.2.1 pypi_0 pypi 
tk 8.6.13 h5226925_1 conda-forge 
tomli 2.0.1 pypi_0 pypi 
tomli-w 1.0.0 pypi_0 pypi 
toolz 0.12.0 pypi_0 pypi 
torch 2.1.2 pypi_0 pypi 
torchvision 0.16.2 pypi_0 pypi 
tornado 6.4 pypi_0 pypi 
tqdm 4.66.1 pypi_0 pypi 
traitlets 5.14.0 pypi_0 pypi 
typer 0.9.0 pypi_0 pypi 
typing-extensions 4.9.0 pypi_0 pypi 
tzdata 2023.3 pypi_0 pypi 
ucrt 10.0.22621.0 h57928b3_0 conda-forge 
urllib3 1.26.18 pypi_0 pypi 
vc 14.3 hcf57466_18 conda-forge 
vc14_runtime 14.38.33130 h82b7239_18 conda-forge 
vispy 0.12.2 pypi_0 pypi 
vs2015_runtime 14.38.33130 hcb4865c_18 conda-forge 
wcwidth 0.2.12 pypi_0 pypi 
webencodings 0.5.1 pypi_0 pypi 
wheel 0.42.0 pyhd8ed1ab_0 conda-forge 
widgetsnbextension 4.0.9 pypi_0 pypi 
wrapt 1.16.0 pypi_0 pypi 
xarray 2023.12.0 pypi_0 pypi 
xmlschema 2.5.0 pypi_0 pypi 
xsdata 23.8 pypi_0 pypi 
xyzservices 2023.10.1 pypi_0 pypi 
xz 5.2.6 h8d14728_0 conda-forge 
yarl 1.9.4 pypi_0 pypi 
zarr 2.15.0 pypi_0 pypi 
zict 3.0.0 pypi_0 pypi 
zipp 3.17.0 pypi_0 pypi 


De: "Guillaume Witz" ***@***.***> 
À: "guiwitz/napari-morphodynamics" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 19 Décembre 2023 16:38:58 
Objet: Re: [guiwitz/napari-morphodynamics] key combination A already used! (Issue #14) 





Hi, 
no worries, I'm grateful that people test the software in its very alpha stage! 
When exactly does this error appear and is this the full error? Can you list again the installed packages with conda list? I don't think this is caused by this plugin as it doesn't have any key bindings. Probably another installed in the same environment.

**Comment by fabricesenger** [comment]
hello,

i removed the plugin and re-installed the latest dev version via pip ... now it starts seamlessly. I think I will have to read the docs now
