### ISSUE TITLE
Cellpose installation

### ISSUE THREAD

**Issue by StojiljkovicVetAna** [guiwitz/napari-morphodynamics#7]
As cellpose doesn't come with napari-morphodynamics, and if cellpose is not installed separately it doesn't work without error messages, it would be nice to have an optional installation like napari-morphodynamics[cellpose]

**Comment by guiwitz** [comment]
Fixed in 5185c87bf93e1a59b7271863645ae007eff0f344. Option also added directly in Morphodynamics.
