### ISSUE TITLE
Cellpose parameters

### ISSUE THREAD

**Issue by StojiljkovicVetAna** [guiwitz/napari-morphodynamics#8]
At the moment when using cellpose as segmentation method, the user can only modify the cell diameter. It would be nice to be able to tune the segmentation using the two thresholds "cellporb" and "model match"

**Comment by guiwitz** [comment]
The two thresholds for cellpose have been added in d0b43ff as well as in [Morphodynamics](https://github.com/guiwitz/MorphoDynamics/commit/2ca4d865f93fd816e345df866868c3a5ac47e57f). Choice of model still needs to be added, currently only default cyto2 is available. As the goal is not to replicate cellpose here, not sure this is necessary. Closing for the moment.
